name: Build Android APK (direct CI build, skip Flutter)

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install and Build Web App
      run: |
        npm install
        CI="" npm run build

    - name: Create Capacitor config
      run: |
        cat > capacitor.config.json << 'EOF'
        {
          "appId": "com.soflu.app",
          "appName": "SoFlu",
          "webDir": "build",
          "bundledWebRuntime": false
        }
        EOF

    - name: Install Capacitor dependencies
      run: npm install @capacitor/cli @capacitor/core @capacitor/android

    - name: Sync Android project
      run: npx cap sync android

    - name: Setup Java for Gradle
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Create local.properties for SDK
      run: echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties

    - name: Sanitize settings.gradle (skip Flutter)
      run: |
        cp android/settings.gradle android/settings.gradle.bak
        echo 'include(":app")' > android/settings.gradle

    - name: Remove Flutter plugin lines from app-level build.gradle
      run: |
        cp android/app/build.gradle android/app/build.gradle.bak
        # Delete any lines mentioning dev.flutter.flutter-plugin
        sed -i '/flutter-plugin/d' android/app/build.gradle
        sed -i '/flutter.gradle/d' android/app/build.gradle

    - name: Setup system Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Build debug APK
      run: |
        cd android
        gradle assembleDebug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
