name: Build Android APK (direct CI build)

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Node setup and install
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install

      - name: Build web assets (ignore lint warnings)
        env:
          CI: ""
        run: npm run build

      - name: Generate Capacitor config
        run: |
          cat > capacitor.config.json << 'EOF'
          {
            "appId": "com.soflu.app",
            "appName": "SoFlu",
            "webDir": "build",
            "bundledWebRuntime": false
          }
          EOF

      - name: Install Capacitor modules
        run: npm install @capacitor/cli @capacitor/core @capacitor/android

      - name: Sync Capacitor Android
        run: npx cap sync android

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Create local.properties
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties

      - name: Sanitize settings.gradle
        run: echo 'include ":app"' > android/settings.gradle

      - name: Setup Gradle CLI
        uses: gradle/actions/setup-gradle@v4

      - name: Build debug APK
        run: |
          cd android
          gradle assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
