name: Android APK (no repo changes)

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build web app
        env:
          CI: ""
        run: npm run build

      - name: Create temporary Capacitor config
        run: |
          cat > capacitor.config.json << 'EOF'
          {
            "appId": "com.soflu.app",
            "appName": "SoFlu",
            "webDir": "build",
            "bundledWebRuntime": false
          }
          EOF

      - name: Install Capacitor dependencies
        run: |
          npm install @capacitor/cli @capacitor/core @capacitor/android

      - name: Sync Capacitor Android project
        run: npx cap sync android

      - name: Set up Java (for Gradle)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Gradle (if no wrapper)
        uses: gradle/actions/setup-gradle@v4

      - name: Build APK with system Gradle
        run: |
          echo "Contents of android/ directory:"
          ls android/
          cd android
          gradle assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
