name: Build Android APK (skip Flutter completely)

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install & build web assets
      run: |
        npm install
        CI="" npm run build

    - name: Create capacitor.config.json
      run: |
        cat > capacitor.config.json <<EOF
        {
          "appId":"com.soflu.app",
          "appName":"SoFlu",
          "webDir":"build",
          "bundledWebRuntime":false
        }
        EOF

    - name: Install Capacitor modules
      run: npm install @capacitor/cli @capacitor/core @capacitor/android

    - name: Sync Android project
      run: npx cap sync android

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Create local.properties
      run: echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties

    - name: Overwrite settings.gradle
      run: echo 'include(":app")' > android/settings.gradle

    - name: Replace app/build.gradle with minimal configuration
      run: |
        cat > android/app/build.gradle <<EOF
        plugins {
          id 'com.android.application'
        }

        android {
          compileSdkVersion 33
          defaultConfig {
            applicationId "com.soflu.app"
            minSdkVersion 21
            targetSdkVersion 33
            versionCode 1
            versionName "1.0"
          }
          buildTypes {
            release {
              minifyEnabled false
            }
          }
        }

        dependencies {
          implementation fileTree(dir: "libs", include: ["*.jar"])
        }
        EOF

    - name: Setup system Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Build debug APK
      run: |
        cd android
        gradle assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
